[tool.ruff]
line-length = 300
select = ["E", "F", "I", "UP"]
target-version = "py311"
ignore = ["D203"]
show-source = true

[tool.black]
line-length = 300
target-version = ['py311']

[tool.pytest.ini_options]
addopts = "-ra --cov"

[tool.coverage.report]
show_missing = true
